// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOztHU92XEzyBRGRFUsTbEDHaMU8otHSM',
    appId: '1:753688786870:web:05c39999a4e42d9ae6f317',
    messagingSenderId: '753688786870',
    projectId: 'todo-tasks-5be1b',
    authDomain: 'todo-tasks-5be1b.firebaseapp.com',
    storageBucket: 'todo-tasks-5be1b.firebasestorage.app',
    measurementId: 'G-F1B3XR32C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVAGayRbDtMlwnByAzA7dU5v7I2JfLHy8',
    appId: '1:753688786870:android:317a007f1803364be6f317',
    messagingSenderId: '753688786870',
    projectId: 'todo-tasks-5be1b',
    storageBucket: 'todo-tasks-5be1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHopwP5qIOp05dEw7OcEU-X2Mc2q2QOUU',
    appId: '1:753688786870:ios:ed652001b4c77fe9e6f317',
    messagingSenderId: '753688786870',
    projectId: 'todo-tasks-5be1b',
    storageBucket: 'todo-tasks-5be1b.firebasestorage.app',
    iosBundleId: 'com.example.todoTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHopwP5qIOp05dEw7OcEU-X2Mc2q2QOUU',
    appId: '1:753688786870:ios:ed652001b4c77fe9e6f317',
    messagingSenderId: '753688786870',
    projectId: 'todo-tasks-5be1b',
    storageBucket: 'todo-tasks-5be1b.firebasestorage.app',
    iosBundleId: 'com.example.todoTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOztHU92XEzyBRGRFUsTbEDHaMU8otHSM',
    appId: '1:753688786870:web:af54eb85aeac88a7e6f317',
    messagingSenderId: '753688786870',
    projectId: 'todo-tasks-5be1b',
    authDomain: 'todo-tasks-5be1b.firebaseapp.com',
    storageBucket: 'todo-tasks-5be1b.firebasestorage.app',
    measurementId: 'G-H54S1NSQ2W',
  );
}
